const products = [
  {
    _id: '1',
    name: 'Sprinkles Plain Half Sleeve T-Shirt',
    image: '/images/sprinkles-plain-half-sleeves-aop-t-shirt-men-s-plain-half-sleeves-aop-t-shirt.jpg',
    description: 'This Sprinkles Plain Half Sleeve AOP T-Shirt is a cute OOTD staple. Style this t-shirt with a pair of joggers and sliders for a casual cool look. Add wayfarers for extra glam. Fits just right - not too tight, not too loose. Classic, lightweight jersey fabric comprising 100% cotton.',
    brand: 'Bewakoof',
    category: 'T-Shirt',
    price: 350,
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    _id: '2',
    name: 'Grey Camo Half Sleeve Camo T-Shirt',
    image: '/images/grey-camo-half-sleeve-camo-t-shirt-men-s-plain-half-sleeve-camo-t-shirt.jpg',
    description:
      'Fits just right - not too tight, not too loose. Classic, lightweight jersey fabric comprising 100% cotton.',
    brand: 'Bewakoof',
    category: 'T-Shirt',
    price: 450,
    countInStock: 7,
    rating: 4.0,
    numReviews: 8,
  },
  {
    _id: '3',
    name: 'Somewhere On Earth T-Shirt',
    image: '/images/somewhere-on-earth-half-sleeve-t-shirt-navy-blue-men-s-printed-t-shirts.jpg',
    description:
      'Fits just right - not too tight, not too loose. Classic, lightweight jersey fabric comprising 100% cotton.',
    brand: 'Bewakoof',
    category: 'T-Shirt',
    price: 400,
    countInStock: 5,
    rating: 3,
    numReviews: 12,
  },
  {
    _id: '4',
    name: 'Iron Man Of War Half Sleeve T-Shirt',
    image: '/images/iron-man-of-war-half-sleeve-t-shirt-avl-men-s-printed-t-shirts.jpg',
    description:
      'It is time to man up and suit up with this Official Marvel Iron Man Of War Half Sleeve T-Shirt. Style it with a pair of jeans, a jacket, and cool sliders to kill the look. Fits just right - not too tight, not too loose. Classic, lightweight jersey fabric comprising 100% cotton.',
      brand: 'Bewakoof',
      category: 'T-Shirt',
      price: 400,
    countInStock: 11,
    rating: 5,
    numReviews: 12,
  },
  {
    _id: '5',
    name: 'Hallows Tri Half Sleeve T-Shirt',
    image: '/images/hallows-tri-half-sleeve-t-shirt--hp-men-s-printed-t-shirts.jpg',
    description:
      'Get a better handle on your games with this Logitech LIGHTSYNC gaming mouse. The six programmable buttons allow customization for a smooth playing experience',
      brand: 'Bewakoof',
      category: 'T-Shirt',
      price: 295,
    countInStock: 7,
    rating: 3.5,
    numReviews: 10,
  },
  {
    _id: '6',
    name: 'Baka Tu Reva De Half Sleeve T-Shirt',
    image: '/images/baka-tu-reva-de-half-sleeve-t-shirt-men-s-printed-t-shirts.jpg',
    description:
      'Let your T-shirt have the last word! Carry your gujju-swag wherever you go. Pair this Baka Tu Reva De Mens T-shirt with joggers & sliders for max comfort.',
      brand: 'Bewakoof',
      category: 'T-Shirt',
      price: 400,
    countInStock: 0,
    rating: 4,
    numReviews: 12,
  },
]

export default products
